
[font]
size = 20

[font.normal]
family = "Hack Nerd Font"
style = "Regular"

[window]
decorations = "buttonless"
dynamic_padding = false
opacity = 0.9
option_as_alt = "OnlyLeft"
startup_mode = "Maximized"

[window.padding]
x = 4
y = 4

[general]
live_config_reload = true
import = [
  "~/.config/alacritty/catppuccin-mocha.toml"
]
